# Generated by Django 3.2.15 on 2022-08-21 01:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PickingDetectionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('worker_id', models.IntegerField()),
                ('busket_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('weight', models.FloatField()),
                ('operation', models.CharField(max_length=40)),
                ('label', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
