# Generated by Django 3.2.15 on 2022-08-21 01:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickingdetectionevent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pickingdetectionevent',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
