# Generated by Django 3.2.15 on 2022-08-21 03:14

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0003_packingdetectionevent_simulationstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDetectionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('worker_id', models.IntegerField()),
                ('package_id', models.IntegerField()),
                ('region_id', models.IntegerField()),
                ('weight', models.FloatField()),
                ('operation', models.CharField(max_length=40)),
                ('label', models.BooleanField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SimulationStatus',
        ),
    ]
