# Generated by Django 3.2.15 on 2022-08-23 11:56

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0005_auto_20220821_0544'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySimulationInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('num_workers', models.IntegerField()),
                ('num_packages', models.IntegerField()),
                ('num_regions', models.IntegerField()),
                ('num_products', models.IntegerField()),
                ('human_error', models.FloatField()),
                ('window_size', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PackingSimulationInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('num_workers', models.IntegerField()),
                ('num_packages', models.IntegerField()),
                ('num_fillings', models.IntegerField()),
                ('human_error', models.FloatField()),
                ('window_size', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PickingSimulationInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('num_workers', models.IntegerField()),
                ('num_buskets', models.IntegerField()),
                ('num_products', models.IntegerField()),
                ('human_error', models.FloatField()),
                ('window_size', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
